### ISSUE TITLE
I have an idea about a 3D Gaussian viewer.

### ISSUE THREAD

**Issue by pkq111** [mkkellogg/GaussianSplats3D#91] opened 2023-12-25 01:59 UTC
I have added camera viewpoint movement in the scene, although it may not be suitable for every model. Perhaps if I can obtain the camera poses from the trained model, it would be possible to automatically handle the camera motion trajectory. What do you think?

**Comment by mkkellogg** [comment] 2023-12-28 22:21
I'm not completely clear on what you're trying to accomplish, are you trying to automate camera movement through the scene? If so you will get the best results/quality from the locations where the original images were captured, but that info is not currently stored in `.splat` or`.ksplat` files. We'd have to either: start including camera pose data in those files, or make it so the app looks for an optional file with that data (like the `cameras.json` file from the original trained models). It does sound like something worthwhile to do, I just don't know when I'd have time to do it :)

**Comment by pkq111** [comment] 2024-01-07 10:16
![image](https://github.com/mkkellogg/GaussianSplats3D/assets/59012199/8e51627f-6a06-4c06-bef1-cc8b80ad95bd)
I have noticed that when I attempt it, the rendered camera orientation is incorrect, while the position of the camera is correct.

**Comment by mkkellogg** [comment] 2024-01-13 23:30
Would this possibly be caused by the bug that was fixed in release [v0.2.1](https://github.com/mkkellogg/GaussianSplats3D/releases/tag/v0.2.1)? You also may need to explicitly set the `initialCameraLookAt` parameter for the `Viewer` constructor.

**Comment by mkkellogg** [comment] 2024-01-24 00:27
Any luck on resolving this issue?

**Comment by pkq111** [comment] 2024-01-24 01:22
No, I guess there might be rotation parameter conversions, but I don't know how they should be converted

**Comment by mkkellogg** [comment] 2024-02-03 03:09
I'm going to close this issue for now, in a future release I'll look into ways to incorporate the original camera positions and orientations into the scene file.

**Closed by mkkellogg** 2024-02-03 03:09 UTC
