### ISSUE TITLE
Splats are not fully shown when streaming is off

### ISSUE THREAD

**Issue by jvandereijk** [mkkellogg/GaussianSplats3D#167] opened 2024-03-19 15:07 UTC
Smaller splats without a background  are not entirely shown since the latest release(s), it looks like the final few percent are not revealed.

See:
https://voluma.ai/show/voluma/demo/yacht3.5x

vs:
https://voluma.ai/show/voluma/demo/yacht3.5x?streaming=true

Maybe this happens with all splats, but bigger splat may not be this obvious.

Update: On mobile (ios) the streaming splat also doesnt seem to fully load, but on both Windows 11 and MacOs it does.

**Comment by jvandereijk** [comment] 2024-03-19 15:13
Closed for now, I thought i had the same issue in the most basic example project, but I can't seem to reproduce it atm.

**Comment by mkkellogg** [comment] 2024-03-19 17:23
I found the cause of this problem and I pushed a fix to the `dev` branch. Would you be able to test with that to see if it resolves your issue?

**Comment by jvandereijk** [comment] 2024-03-19 17:59
I tested the dev branch. It looks great now, Thanks!

**Comment by mkkellogg** [comment] 2024-03-20 16:17
The `npm` package has been updated, could you verify if the issue is fixed there as well?

**Comment by mkkellogg** [comment] 2024-03-21 15:16
Going to close this for now, if you encounter the problem again in the latest version of the `npm` package, let me know.

**Closed by mkkellogg** 2024-03-21 15:16 UTC
