### ISSUE TITLE
my splat is rotating in vertical plane of my screen

### ISSUE THREAD

**Issue by sumanttyagi** [mkkellogg/GaussianSplats3D#246] opened 2024-06-03 21:18 UTC
let's say i want to fix rotation in only horizontals plane screen the scene is just revolving 
can you please help me

**Comment by mkkellogg** [comment] 2024-06-03 23:50
Can you show me the code you're using right now? And just to clarify, the effect you are trying to achieve is rotation in the horizontal plane relative to the screen?

**Comment by mkkellogg** [comment] 2024-06-14 03:11
I'm sorry, I am still a bit confused as to what the problem is. Are you trying to rotate the scene using the mouse, or by using code (for example, by passing `rotation` to `Viewer.addSplatScene()`)?

**Comment by mkkellogg** [comment] 2024-06-14 03:44
Ah, this is happening because the splats are not aligned with the scene's natural axes. Press the `U` key to visualize the scene's axes, you'll see a green arrow pointing up (the `Y` axis). Then you can use the left and right arrow keys to rotate the scene around the forward axis (the direction the camera is facing) and with some trial and error you can align the scene with the natural axes. The orbiting mouse controls don't let you rotate a full 360 degrees around the center of rotation, so that's why you're seeing the limitations you're seeing.

Once you have your scene aligned, you can press the `I` key to see the camera's "up" vector, and pass that as a constructor parameter to `Viewer` next time you load the scene, and it should start out aligned correctly.

**Comment by mkkellogg** [comment] 2024-06-24 18:44
Just wanted to check in, did the above approach work for you?

**Comment by mkkellogg** [comment] 2024-06-28 22:33
Closing this for now, please let me know if you still need help with this.

**Closed by mkkellogg** 2024-06-28 22:33 UTC
