### ISSUE TITLE
How to add mouse events to a camera that allow rotation around itself？

### ISSUE THREAD

**Issue by 2579024264** [mkkellogg/GaussianSplats3D#185] opened 2024-04-02 08:04 UTC
I expect the camera to rotate around itself through the mouse event, with the coordinate position unchanged. I have annotated the events listening to W, S, A, and D in OrbitControls, but the following actions did not work！
`switch (e.code) {
                case 'ArrowLeft':
                    this.camera.up.transformDirection(tempMatrixLeft);
                break;
                case 'ArrowRight':
                    this.camera.up.transformDirection(tempMatrixRight);
                break;
                case 'KeyW':
                    this.camera.rotateX(0.05);
                    break;
                case 'KeyS':
                    this.camera.rotateX(-0.05);
                    break;
                case 'KeyA':
                    this.camera.rotateY(0.05);
                    break;
                case 'KeyD':
                    this.camera.rotateY(-0.05);
                    break;
                case 'KeyC':
                    this.showMeshCursor = !this.showMeshCursor;
                    break;
                case 'KeyP':
                    this.showControlPlane = !this.showControlPlane;
                break;
                case 'KeyI':
                    this.showInfo = !this.showInfo;
                    if (this.showInfo) {
                        this.infoPanel.style.display = 'block';
                    } else {
                        this.infoPanel.style.display = 'none';
                    }
                break;
            }`

**Comment by mkkellogg** [comment] 2024-04-07 00:10
The issue is that the camera is bound to the instance of `OrbitControls` that is used by the viewer, and those always make sure that the camera is pointed at its internal focal point (called `target`). Your code won't work unless you disable usage of those controls.

**Comment by mkkellogg** [comment] 2024-04-16 02:16
I'm going to close this for now, let me know if you need any further help with this.

**Closed by mkkellogg** 2024-04-16 02:16 UTC
