### ISSUE TITLE
Incorrect Rendering results on Apple Vision Pro

### ISSUE THREAD

**Issue by kotauchisunsun** [mkkellogg/GaussianSplats3D#128] opened 2024-02-18 12:15 UTC
I viewed GaussianSplats3D in WebVR mode on AppleVisionPro.
It generally works for the areas where splats are present, but did not work well for the areas where splats are not present.

Video of the areas where splats are present.
https://twitter.com/kotauchisunsun/status/1758524300318191932

Video of the areas where splats are not present.
https://twitter.com/kotauchisunsun/status/1759187480174305319

Here is the source code.
```<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>3D Gaussian Splat Demo - VR Garden</title>
  <script type="text/javascript" src="js/util.js"></script>
  <script type="importmap">
    {
        "imports": {
            "three": "./lib/three.module.js",
            "@mkkellogg/gaussian-splats-3d": "./lib/gaussian-splats-3d.module.js"
        }
    }
  </script>
  <style>

    body {
      background-color: #000000;
      height: 100vh;
      margin: 0px;
    }

  </style>

</head>

<body>
  <script type="module">
    import * as GaussianSplats3D from '@mkkellogg/gaussian-splats-3d';
    import * as THREE from 'three';
    const viewer = new GaussianSplats3D.Viewer({
      'initialCameraPosition': [-0.77493, -0.54359, 1.63199],
      'initialCameraLookAt': [0.20786, -0.68154, -0.27311],
      'webXRMode': GaussianSplats3D.WebXRMode.VR,
      'gpuAcceleratesSort': false,
      'sharedMemoryForWebWorkers': false
    });
    let path = 'assets/data/bonsai/bonsai.ksplat';
    viewer.addSplatScene(path, {
        'rotation': new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0.01933, -0.75830, -0.65161).normalize(), new THREE.Vector3(0, 1, 0)).toArray(),
        'scale': [0.25, 0.25, 0.25],
        'position': [0, 1, 0]
    })
    .then(() => {
        viewer.start();
    });
  </script>
</body>

</html>
```

Thanks for the nice library!

**Comment by mkkellogg** [comment] 2024-02-19 00:19
Unfortunately I can't really debug this issue because I don't have an Apple Vision Pro, and as of right now I don't plan on buying one until the price comes down :) If anyone else has some insights here, it would be great to get some help!

**Comment by JiamingSuen** [comment] 2024-02-19 01:48
The same issue can be reproduced in the visionOS simulator.

**Comment by did66** [comment] 2024-02-27 07:55
> The same issue can be reproduced in the visionOS simulator. There is no error message in the console. I would love to provide more information if needed.
> 
>  output.mp4

Why do I show "AR NOT SUPPORTED" 
![8b8333523dc1b2c6bbf50b0270056e4](https://github.com/mkkellogg/GaussianSplats3D/assets/15080963/1c69d473-90c1-4b05-bc4a-c66322dcfbb1)
Can you help me?

**Comment by did66** [comment] 2024-03-04 09:47
> The same issue can be reproduced in the visionOS simulator. There is no error message in the console. I would love to provide more information if needed.
> 
>  output.mp4

Have you find a solution? 
I'm also troubled by this issue.  
or Do you have any alternative methods? 
thanks

**Comment by JiamingSuen** [comment] 2024-03-04 13:17
> Have you find a solution? I'm also troubled by this issue. or Do you have any alternative methods? thanks

No, I have not. I tried a few things and didn't have enough time to get it right. Let's hope the author would allocate some time in the future :)

**Comment by dlazares** [comment] 2024-03-15 06:06
I discussed this in #127 by accident. The old drop in viewer method was working before on AVP.

**Comment by dlazares** [comment] 2024-03-16 02:45
@mkkellogg so it's definitely the dropin viewer vs non-dropin viewer. I tested on the latest commit.

**Comment by mkkellogg** [comment] 2024-03-16 16:13
@dlazares Good to know, I'll try to find some time this weekend to dig into this issue.

**Comment by mkkellogg** [comment] 2024-03-16 20:43
@dlazares Would you be able to share the code you used to reproduce the issue, as well as an example of where it works properly?

**Comment by mkkellogg** [comment] 2024-04-03 01:40
I know this is a bit late, bit I have WIP branch that I think addresses this issue: [orthographic_projection](https://github.com/mkkellogg/GaussianSplats3D/tree/orthographic_projection) -- If you want to try it and see if it fixes the issue. I'll merge it into `main` and push out a release soon.

**Comment by JiamingSuen** [comment] 2024-04-06 20:44
I can confirm that the rendering issue has been fixed in the latest `main` branch. Aside from the incorrect color gamma (which is a known issue for WebXR mode on visionOS: [ref](https://bugs.webkit.org/show_bug.cgi?id=270465)), the alpha falloff on the splat edges seems weird. I noticed the same problem in a [Metal implementation](https://github.com/scier/MetalSplatter/). Any ideas why this could go wrong? Thanks.

https://github.com/mkkellogg/GaussianSplats3D/assets/8616975/28d67709-f91d-4817-ba46-3522cb6853af

**Comment by JiamingSuen** [comment] 2024-04-08 18:38
@mkkellogg I noticed a new problem after this bug was fixed on Vision Pro. Splat scales (or alphas?) are wrong only in stereo rendering mode on Quest headsets. This can be verified easily through the [WebXR Emulator](https://chromewebstore.google.com/detail/immersive-web-emulator/cgffilbpcibhmcfbgggfhfolhkfbhmik) provided by Meta. I've also checked that this bug can be reproduced on the headset (but no screen recordings though since it's so laggy).

https://github.com/mkkellogg/GaussianSplats3D/assets/8616975/176d93b6-f36e-4833-8be5-a220269c3c6c

BTW, any comments on the previous questions would also be nice! I tried a few things and couldn't get it right. It seems [this repo](https://github.com/laanlabs/metal-splats/) does not have the hard alpha falloff problem.

**Comment by mkkellogg** [comment] 2024-04-08 20:39
I will take a look at the stereo rendering bug, hopefully it's an easy fix. As for the hard alpha falloff, I'm guessing it might have something to do with the fact that in my viewer the splats are rendered as quads that are aligned to the splat's 2D screen-space axes that are clipped at sqrt(8) standard deviations. I try to document that in the shader code. The value sqrt(8) may seem somewhat arbitrary; I'm mainly using it because it is (less obviously) the same cutoff that is used in other online viewers like [Antimatter's splat viewer](https://github.com/antimatter15/splat) and the  [Unity Gaussian splat viewer](https://github.com/aras-p/UnityGaussianSplatting) You could try increasing that value here: https://github.com/mkkellogg/GaussianSplats3D/blob/0f5b839b4f6d30d5c65b487b20844f4b2cad61e2/src/SplatMesh.js#L157 and then its corresponding squared value here: https://github.com/mkkellogg/GaussianSplats3D/blob/0f5b839b4f6d30d5c65b487b20844f4b2cad61e2/src/SplatMesh.js#L357
(I probably need to have better variable names :) )

In the [metal-splats](https://github.com/laanlabs/metal-splats) repo they use the original approach to rendering, which is calculate a bounding box that is aligned to the screen and has a side length that is the maximum of the 2 screen-space eigen values scaled by 3.0 standard deviations: https://github.com/laanlabs/metal-splats/blob/4a1c3f05c06a3ddf5f7358d6aaadd889f3e47d64/MetalSplat/SplatShaders.metal#L285. This means their bounding box is much less compact than the one I calculate in my viewer, and maybe that's why they don't have a hard alpha fall-off issue.

I would also guess that the gamma issue you mentioned might be exacerbating the issue in my viewer. However this is all just a guess! I will investigate further and get back to you once I figure something out.

**Comment by Fly2Spring** [comment] 2024-04-17 04:30
> @mkkellogg I noticed a new problem after this bug was fixed on Vision Pro. Splat scales (or alphas?) are wrong only in stereo rendering mode on Quest headsets. This can be verified easily through the [WebXR Emulator](https://chromewebstore.google.com/detail/immersive-web-emulator/cgffilbpcibhmcfbgggfhfolhkfbhmik) provided by Meta. I've also checked that this bug can be reproduced on the headset (but no screen recordings though since it's so laggy).
> 
>  resized.mp4 
> BTW, any comments on the previous questions would also be nice! I tried a few things and couldn't get it right. It seems [this repo](https://github.com/laanlabs/metal-splats/) does not have the hard alpha falloff problem.

I'm stucked with the same bug on Quest 3, any updates? Thanks!!

**Comment by mkkellogg** [comment] 2024-04-17 23:26
So I think the issue is that three.js (and my viewer) can't tell when WebXR is rendering in stereo mode, and therefore don't know that the aspect ratio needs to be adjusted in that case. Basically when rendering in stereo mode, the viewport width value that is sent to the shader for the splat renderer needs to be halved. I'll keep digging!

**Comment by mkkellogg** [comment] 2024-04-18 03:44
So I have a WIP branch that I think addresses the issue (at least in the WebXR emulator extension): https://github.com/mkkellogg/GaussianSplats3D/tree/fix_webxr_stereo. Can you try that out and let me know if it works for you?

**Comment by JiamingSuen** [comment] 2024-04-18 04:31
> So I have a WIP branch that I think addresses the issue (at least in the WebXR emulator extension): https://github.com/mkkellogg/GaussianSplats3D/tree/fix_webxr_stereo. Can you try that out and let me know if it works for you?

It works perfectly on a Quest 3!

**Comment by mkkellogg** [comment] 2024-04-18 18:07
Great! I'll hopefully get a release out with this fix soon :)

**Comment by mkkellogg** [comment] 2024-04-22 17:42
The latest release [v0.3.9](https://github.com/mkkellogg/GaussianSplats3D/releases/tag/v0.3.9) now has this fix in it :)

**Comment by mkkellogg** [comment] 2024-04-23 14:47
I'll close this for now, let me know if you run into any other problems!

**Closed by mkkellogg** 2024-04-23 14:47 UTC
Labels: help wanted
