### ISSUE TITLE
can not load MCMC gaussian splat properly

### ISSUE THREAD

**Issue by dekahobby** [mkkellogg/GaussianSplats3D#299] opened 2024-08-08 01:02 UTC
i have problem load new MCMC splat on three.js build, its like something block the splat, like clipping mask
can you check it please? i use post shot for build gaussian splatting mcmc

![on postshot viewer](https://github.com/user-attachments/assets/753735af-e182-47fb-8427-97165fc48e18)
![mcmc on three js viewer](https://github.com/user-attachments/assets/75cfaddb-21bc-48ee-bff2-18de259c0f26)

**Comment by mkkellogg** [comment] 2024-08-08 02:20
I haven't tried loading an MCMC scene, so I'm not surprised it doesn't work correctly :) Can you post the `.ply` file so I can debug?

**Comment by dekahobby** [comment] 2024-08-08 03:13
some sample, fast process for preview only

https://drive.google.com/file/d/1C471aAepHEsBVDqXhnbp01OPx_xDXkbI/view?usp=sharing

**Comment by mkkellogg** [comment] 2024-08-09 02:03
So the problem with this scene is that it has huge dimensions with a huge amount of empty space. If you try loading it in SuperSplat you can see what I mean. The average scene position is `[x: 7.068240, y: -13.41508, z: -10.563791]`, but the dimensions are:

X: -8487363 to  21661588
Y:  -7213492 to 16279433
Z: -18439536 to  7261742.5

Can you try cropping it down to the relevant area and try again?

**Comment by newguy123-creator** [comment] 2024-08-28 06:42
> So the problem with this scene is that it has huge dimensions with a huge amount of empty space. If you try loading it in SuperSplat you can see what I mean. The average scene position is `[x: 7.068240, y: -13.41508, z: -10.563791]`, but the dimensions are:
> 
> X: -8487363 to 21661588 Y: -7213492 to 16279433 Z: -18439536 to 7261742.5
> 
> Can you try cropping it down to the relevant area and try again?
> 
> P.S. The reason my viewer can't handle extremely large dimensional ranges is that it uses a counting sort algorithm to sort the splats, which performs poorly on large ranges.

Any plans to improve this for large scenes? Most of our scenes are large also for construction. IE typical scene could be 200 to 500 meter by 400 meter or larger. Don't know what that translates to in splat coordinates though...

**Comment by mkkellogg** [comment] 2024-09-03 01:55
Right now, in theory, you should be able to load MCMC Gaussian splatting scenes since the file structures are the same as vanilla Gaussian splatting. The issue is the scene bounds -- they can't be too extreme, like the example mentioned above. The precise limit to scene bounds is difficult to know unfortunately. A scene that is 200 x 500 x 400 should be fine, as long as the splat coordinates fall into those ranges.

**Comment by mkkellogg** [comment] 2024-09-08 02:59
I've made some updates in the [memory-optimizations](https://github.com/mkkellogg/GaussianSplats3D/tree/memory-optimizations) branch that might help with this issue. First you should set the `Viewer` parameter `integerBasedSort` to `false`. Next, set the new `Viewer` parameter `splatSortDepthMapRange` to 1048576. (You might need to set it to a higher value and if you do, make sure the `Viewer` parameter `sharedMemoryForWorkers` is set to `true`). I'll close this issue for now, but feel free to reach out if you still need help.

**Closed by mkkellogg** 2024-09-08 02:59 UTC

**Comment by mkkellogg** [comment] 2024-09-08 19:19
Update: the parameter has been renamed to `splatSortDistanceMapPrecision` and now represents the precision of the range. For a range of 1048576 (20-bit), use a value of 20 for `splatSortDistanceMapPrecision`.
